development: &default
  host: localhost
  transport_options:
    request:
      timeout: !!integer 300
test:
  <<: *default
staging:
  <<: *default
production:
  host: <%= ENV['BONSAI_URL'] %>
  transport_options:
    request:
      timeout: !!integer 300