development: &default
  host: localhost
  transport_options:
    request:
      timeout: !!integer 300
test:
  <<: *default
staging:
  <<: *default
production:
  host: https://9fqe5wzca2:vq3pz8yng7@fir-927051852.us-east-1.bonsaisearch.net:443
  transport_options:
    request:
      timeout: !!integer 300